const mongoose = require('mongoose');
const Farm = require('../models/farms');
const fs = require('fs')
mongoose.connect('mongodb://localhost:27017/farmanalytics', { useNewUrlParser: true });




let dataArr = []


function parse(filename) {

    let dataCSV = fs.readFileSync(filename, 'utf-8').trim()

    dataArr = dataCSV.replace(/(\[|\"|\]|\\|\')/g, '').split('\n').map(i => i.split(','))

    for (let i = 0; i < dataArr.length; i++) {
        dataArr[i].splice(90, 4)

    }


}


parse('data.csv')
// console.log(dataArr)


let schemaVariablesRU = ['CODE ID',
    'Давность симптомов',
    'Длительность приступа (в днях)',
    'Интенсивность боли (ВАШ)',
    'Тип боли',
    'Частота (раз в месяц)',
    'Локализация боли (сторона)',
    'Локализация боли (анатомическая)',
    'Боль в теле',
    'Слабость',
    'Фото/фоно фобия',
    'Тошнота',
    'Аура 1',
    'Аура 2',
    'Триггер 1',
    'Триггер 2',
    'Неврологический дефицит',
    'Семейный анамнез по мигрени',
    'Возраст',
    'Пол',
    'Аллергия',
    'Сердечно-сосудистые заболевания',
    'Заболевания ЦНС',
    'Заболевания ЖКТ',
    'Эндокринные заболевания',
    'Поражения костно-мышечной системы',
    'Психические заболевания',
    'Респираторные заболевания',
    'Инсульт + мигрень',
    'МРТ - выдано направление',
    ' но результаты не указаны',
    'МРТ - патологии не выявлено',
    'МРТ - выявлены отклонения',
    'КТ -выдано направление',
    ' но результаты не указаны',
    'КТ - патологии не выявлено',
    'КТ - выявлены отклонения',
    'Рентген -  выдано направление',
    ' но результаты не указаны',
    'Рентген - патологии не выявлено',
    'Рентген - выявлены отклонения',
    'ЭЭГ - выдано направление',
    ' но результаты не указаны',
    'ЭЭГ - патологии не выявлено',
    'ЭЭГ - выявлены отклонения',
    'УЗИ - выдано направление',
    ' но результаты не указаны',
    'УЗИ - патологии не выявлено',
    'УЗИ - выявлены отклонения',
    'Диагноз поставлен',
    'Бассейн',
    'Гирудотерапия',
    'Диетотерапия',
    'Иглорефлексотерапия',
    'ЛФК',
    'Массаж',
    'Психотерапия',
    'Физиотерапия',
    'Количество обращений по мигрени',
    'Кардиолог',
    'Физиотерапевт',
    'Мануальный терапевт',
    'Невролог',
    'Офтальмолог',
    'Психотерапевт',
    'Терапевт',
    'Вызов СМП',
    'Госпитализации',
    'Дней госпитализации',
    'Больничный лист',
    'Дней б/л',
    'Сопутсвующая терапия (гормонотерапия',
    ' гормональная контрацепция)',
    'бетаблокаторы',
    'антиконвульсанты',
    'антидепрессанты',
    'миорелаксант',
    'ботокс',
    'триптаны',
    'алкалоиды',
    'противорвотные',
    'анальгетики',
    'антихолинэстеразные',
    'анксиолитики',
    'нейролептики',
    'ноотропы',
    'корректоры',
    'антагонисты',
    'метаболики',
    'антигипоксанты',
    'Кому назначены ФД',
    'Клиника'
]
let schemaVariablesEng = ['CODE ID',
    'Longevity of symptoms.',
    'Seizure duration (in days)',
    'Pain intensity (YOUR).',
    'Type of pain.',
    'Frequency (once a month)',
    'Localization of pain (side)',
    'Pain localization (anatomical).',
    'Pain in the body.',
    'Weakness.',
    'Photo/phono phobia.',
    'Nausea.',
    'Aura 1.',
    'Aura 2.',
    'Trigger 1.',
    'Trigger 2.',
    'Neurological Deficit.',
    'Family history of migraine.',
    'Age',
    'Paul.',
    'Allergies',
    'Cardiovascular disease.',
    'CNS Diseases.',
    'Gastrointestinal diseases.',
    'Endocrine Diseases',
    'Lesions of the musculoskeletal system.',
    'Mental illness.',
    'Respiratory Diseases',
    'Stroke + migraine.',
    'MRI is a referral',
    'but the results are not indicated',
    'MRI - no pathology detected.',
    'MRI - Discrepancies detected',
    'KT\'s been given a direction',
    'but the results are not indicated',
    'KT - no pathology detected.',
    'C.T. - Discrepancies detected.',
    'X-rays - referral issued',
    'but the results are not indicated',
    'No X-ray pathology detected.',
    'X-rays - Discrepancies detected.',
    'EEG - referral issued',
    'but the results are not indicated',
    'EEG - no pathology detected.',
    'EEG - Discrepancies detected.',
    'Ultrasound is a referral',
    'but the results are not indicated',
    'No ultrasound pathology detected.',
    'Ultrasound - Discrepancies detected.',
    'Diagnosis made.',
    'Swimming pool.',
    'Gyrudotherapy.',
    'Diet Therapy.',
    'Igloreflexotherapy.',
    'LFK.',
    'Massage.',
    'Psychotherapy',
    'Physiotherapy',
    'Number of migraine calls.',
    'Cardiologist.',
    'Physiotherapist.',
    'Chiropractor.',
    'Neurologist.',
    'Ophthalmologist.',
    'Psychotherapist.',
    'The therapist.',
    'Call the SOC.',
    'Hospitalization',
    'Hospitalization Days.',
    'Hospital Leaf',
    'Days of b/l',
    'Concomitant therapy (hormone therapy)',
    'Hormonal contraception',
    'beta-blockers',
    'Anticonvulsants.',
    'Antidepressants.',
    'Myorelaxant.',
    'Botox',
    'Tryptans.',
    'Alkaloids.',
    'anti-vomiting.',
    'analgesics.',
    'Anticholinesterase.',
    'Anxiolytics.',
    'Neuroleptics.',
    'Nootropics.',
    'proofreaders',
    'Antagonists.',
    'Metabolics.',
    'Anti-hypoxicants.',
    'To whom are the FBI assigned?',
    'Clinic'
]

let newNewEng = ['codeID',
    'sympDuration',
    'attackDuration',
    'painIntencity',
    'painType',
    'frequancy',
    'localizationSide',
    'localizationAnatomy',
    'bodyPain',
    'weakness',
    'phobia',
    'nausea',
    'aura1',
    'aura2',
    'trigger1',
    'trigger2',
    'neurologicalDeficit',
    'anamnesis',
    'age',
    'gender',
    'allergy',
    'cardiovascular',
    'cns',
    'tract',
    'endocrine',
    'skeletalmuscular',
    'mental',
    'respiratory',
    'insultmigranie',
    'mriDirection',
    'mriGood',
    'mriBad',
    'ctDirection',
    'ctGood',
    'ctBad',
    'xraysDirection',
    'xraysGood',
    'xraysBad',
    'eegDirection',
    'eegGood',
    'eegBad',
    'ultrasoundDirection',
    'ultrasoundGood',
    'ultrasoundBad',
    'diagnosed',
    'pool',
    'gyrudotherapy',
    'diet',
    'igloreflex',
    'lfk',
    'massage',
    'psychotherapy',
    'physiotherapy',
    'magraineCalls',
    'cardiologist',
    'physiotherapist',
    'manualtherapist',
    'neurologist',
    'ophtalmologist',
    'psychotherapist',
    'therapist',
    'socCall',
    'hospitalization',
    'hospitalizationDays',
    'hospitalLeaf',
    'leafDays',
    'concomitantTherapy',
    'betaBlockers',
    'anticonvulsants',
    'antidepressants',
    'myorelaxant',
    'botox',
    'tryptans',
    'alkaloids',
    'antiVomiting',
    'analgesics',
    'anticholinesterase',
    'anxiolytics',
    'neuroleptics',
    'nootropics',
    'proofreaders',
    'antagonists',
    'metabolics',
    'antiHypoxicants',
    'patient',
    'clinic'
]

async function seedBase() {
    for (let i = 1; i < dataArr.length; i++) {
        const farmData = {}
        for (let j = 0; j < dataArr[i].length; j++) {
            farmData[newNewEng[j]] = dataArr[i][j]
        }
        let newFarm = new Farm(farmData)
        await newFarm.save()
    }
    mongoose.disconnect()
}

seedBase()

async function name() {
    let user = await Farm.find({codeID:'"RU05-208114"'})
    console.log(user)
}

// name()